version: '3.1'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - MONGODB_URI=mongodb://mongoadmin:secret@mongodb:27017/paytmdb?authSource=admin
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - backend-network

  mongodb:
    build:
      context: ./mongo_db
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb/data:/data/db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
